config/routes.rb
Rails.application.routes.draw do
  root 'elevators#index'
  resources :elevators, only: :index
  get 'elevators/move/:floor' => 'elevators#move', as: 'elevators_move'
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/elevators_controller.rb
class ElevatorsController < ApplicationController
  before_action :set_elevator

  def index; end

  def move
    reach_floor = MyElevator::Factory.instance.reach_floor
    reach_floor.subscribe(MyElevator::Level.new)
    reach_floor.subscribe(MyElevator::Doors.new)

    @elevator.mark_floor params[:floor]
    @elevator.start_moving

    redirect_to action: :index
  end

  private

  def set_elevator
    @elevator = MyElevator::Factory.instance.elevator
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/elevators_helper.rb
module ElevatorsHelper
  def active_floor(current_floor, floor)
    return 'item active' if current_floor == floor
    'item'
  end
end

app/views/elevators/index.html.erb
<div class="row">
  <div class="icon-bar vertical">
    <% @elevator.floors.each do |floor| %>
      <%= link_to elevators_move_path(floor), class: active_floor(@elevator.current_floor, floor) do %>
        <i class="fa fa-stop-circle"></i>
        <label><%= floor %></label>
      <% end %>
    <% end %>
  </div>
</div>

app/views/elevators/move.html.erb
<div class="row">
  <div class="icon-bar vertical">
    <% @elevator.floors.each do |floor| %>
      <%= link_to elevators_move_path(floor), class: active_floor(@elevator.current_floor, floor) do %>
        <i class="fa fa-stop-circle"></i>
        <label><%= floor %></label>
      <% end %>
    <% end %>
  </div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />

    <title><%= content_for?(:title) ? yield(:title) : 'Elevator' %></title>

    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/font-awesome/4.5.0/css/font-awesome.min.css">
    <%= stylesheet_link_tag    'application' %>
    <%= javascript_include_tag 'vendor/modernizr' %>
    <%= javascript_include_tag 'application' %>
    <%= csrf_meta_tags %>
  </head>

  <body>
    <%= yield %>
    <div id="ember-app"></div>
  </body>
</html>